### ISSUE TITLE
Crash when CPQ query is faulty

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#5] opened 2018-10-04 04:52 UTC
I managed to cause a crash with polmineR, but obviously, this is a RcppCWB issue.

```r
count("GERMAPARL", query = 'Flüchtling.*"', cqp = TRUE)
```

**Comment by ablaette** [comment] 2021-02-22 08:54
I cannot reproduce this error.  A better example would have been:

```r
RcppCWB::cqp_query(corpus = "GERMAPARL", query = 'Flüchtling.*"')
```

But it aborts gracefully:
CQP Error:
	Corpus ``'' is undefined
CQP Error:
	CQP Syntax Error: 
Synchronizing to end of line ... 
ERROR: Cannot parse the CQP query.
NULL

Given that polmineR includes additional checks whether the query is correct, I close this issue.

**Closed by ablaette** 2021-02-22 08:54 UTC
